name: sprouse
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37975
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#13171a'
    - '#8199bd'
    - '#f8f6f7'
    - '#484d47'
    - '#9e6442'
  brandStrength: 0.1875
  lightness: 0.7429079781286418
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
