name: sprouse
favicon: null
layout_spectrum: 0.40596329304389656
typography_spectrum: 0.22667449968867004
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.04151927772909403
  lightness: 0.7429079781286418
  saturation: 0.1084852737840265
  rhythmicContrast: 0.3659073612652719
purpose: []
